### ISSUE TITLE
Performance optimizations are needed

### ISSUE THREAD

**Issue by kaphula** [Pyrdacor/freeserf.net#106]
I have not familiarized myself with the implementation details, but there is something too heavy going on performance wise. My laptop uses 100% of its single core almost all of the time the game is running which should not be the case, not even with C# implementation. Any thoughts, plans or ideas regarding this issue?

**Comment by Pyrdacor** [comment]
I have no such big performance issues but there are very likely much non-optimal implementations and room for optimization. I ported the whole game in very short time and didn't understand all of the code back then. Moreover the AI is a big source of performance issues as there is a lot of calculation going on and the testing was very rudimentary caused by lack of time and capacities.

Profiling etc is on my todo list but there are many things on that list unfortunately. Every helping hand is appreciated.

**Comment by Pyrdacor** [comment]
I have 15-20% CPU usage, 17-23% GPU usage and around 120 MB memory usage. So there seem to be no performance issue in general. The release build is even better using only 70-75 MB memory and CPU usage wasn't above 18%.

**Comment by Pyrdacor** [comment]
@kaphula Can you please verify if the performance issues only occur on a specific OS or with specific settings (e.g. debugging active) and then re-open if you have more information?
