### ISSUE TITLE
Geologists rushing flag

### ISSUE THREAD

**Issue by Vershner** [Pyrdacor/freeserf.net#48]
I've never tried to sent even one geologist to this flag, but they keep on coming over and over. 

![geol-rush](https://user-images.githubusercontent.com/41204375/55292340-5fb5ae80-53e1-11e9-82fc-3288cef11650.png)

[GEOL-RUSH.zip](https://github.com/Pyrdacor/freeserf.net/files/3026914/GEOL-RUSH.zip)

**Comment by Pyrdacor** [comment]
This was a very funny bug. Let me explain. The AI checks mountains near their border. If they find a flag there, they won't bother placing one and send their geologists there. But there was no check if the flag belongs to the AI player. Moreover when sending a geologists, the player is automatically determined by the flag owner and not by the player who requested the geologist. Therefore the near AI player (the red one) ordered your geologists to that flag. :D

This is now fixed in patch 1.9.14 by checking that the flag is owned by the AI.
